### ISSUE TITLE
Oracle Cloud event catcher fails due to private method

### ISSUE THREAD

**Issue by agrare** [ManageIQ/manageiq-providers-oracle_cloud#66]
```
ent_monitor) EMS [] as [ocid1.user.oc1..aaaaaaaa3yzc47pwxfbrjdnft6ptoxw45vu4poctevj2e2a666s2watp3hxa] Started Event Monitor Thread
ERROR -- evm: MIQ(ManageIQ::Providers::OracleCloud::CloudManager::EventCatcher::Runner#start_event_monitor) EMS [] as [ocid1.user.oc1..aaaaaaaa3yzc47pwxfbrjdnft6ptoxw45vu4poctevj2e2a666s2watp3hxa] Event Monitor Thread aborted because [private method `event_stream' called for #<ManageIQ::Providers::         OracleCloud::CloudManager::EventCatcher::Runner:0x00005626cbe0da60>]
ERROR -- evm: [NoMethodError]: private method `event_stream' called for #<ManageIQ::Providers::OracleCloud::CloudManager::EventCatcher::Runner:0x00005626cbe0da60>  Method:[block (2 levels) in <class:LogProxy>]
ERROR -- evm: /opt/IBM/infrastructure-management-gemset/bundler/gems/bluecf-providers-oracle_cloud-c988b7356399/app/models/manageiq/providers/oracle_cloud/cloud_manager/event_catcher/runner.rb:43:in `ensure_event_stream'
  /opt/IBM/infrastructure-management-gemset/bundler/gems/bluecf-providers-oracle_cloud-c988b7356399/app/models/manageiq/providers/oracle_cloud/cloud_manager/event_catcher/runner.rb:10:in `monitor_events'
  /var/www/miq/vmdb/app/models/manageiq/providers/base_manager/event_catcher/runner.rb:156:in `block in start_event_monitor'
```

Version: https://github.com/ManageIQ/manageiq-providers-oracle_cloud/commit/c988b73 (morphy)

**Comment by Fryguy** [comment]
Updated the OP to show that commit is on morphy.
